const COLORS = {
  WHITE: '#EFF6FB',
  BLUE_PRIMARY: '#141C2F',
  BLUE_SECONDARY: '#1F2A48',
  BLUE_TERNARY: '#107CFA',
  BLUE_QUARTERNARY: '#2A5DA3',
  GRAY_PRIMARY: '#BDC5D9',
  GRAY_SECONDARY: '#45516B'
};

export { COLORS };
